FROM ubuntu:22.04

RUN apt update && \
    apt install -y git cargo python3 libssl-dev g++ extra-cmake-modules

# https://facebook.github.io/watchman/docs/install.html#-building-from-source
# https://facebook.github.io/watchman/docs/install.html#prebuilt-binaries-2
RUN git clone https://github.com/facebook/watchman.git -b v$WATCHMAN_VERSION && \
    cd /watchman && \
    ./install-system-packages.sh && \
    ./autogen.sh && \
    mkdir -p /usr/local/{bin,lib} /usr/local/var/run/watchman && \
    cp built/bin/* /usr/local/bin && \
    cp built/lib/* /usr/local/lib || true && \
    chmod 755 /usr/local/bin/watchman && \
    chmod 2777 /usr/local/var/run/watchman && \
    rm -rf /tmp/* && \ 
    rm -rf /watchman
# The "|| true" in the cp command is necessary because in some cases, 
# the system already has all the necessary deps and the cp command
# throws an error because there is no file in the folder "built/lib/" folder
# https://github.com/facebook/watchman/issues/1086#issuecomment-1396259685

RUN watchman -v